/-
Copyright (c) 2026 Yueheng Shi. All rights reserved.
Released under the Apache License, Version 2.0.
Authors: Yueheng Shi
-/
import Definitions.Def_PvsNP
import QIP.Execution
import QIP.Decode

/-!
# Q15 — the classes `QIP` and `QIPm k`

* `PromiseProblem`: disjoint sets of yes and no instances over binary strings;
  `ofLanguage L = (L, Lᶜ)` embeds a language (`Language Bool = Set (List Bool)`, as in
  `PvsNP`).
* `VerifierFamily`: for every input `x`, a **valid** description `desc x` (`Desc.Valid`:
  in-range wires, verifier ownership of every gate, alternating messages, output in the
  private register). It is generated by a polynomial-time computable function
  (`PvsNP.PolyTimeComputable`) that prints exactly `encode (desc x)`. One natural-coefficient
  polynomial bounds the number of messages, the number of wires and the number of gates (it is
  evaluated at `x.length`, so lengths `0` and `1` are included). Any classical input register
  must be prepared by explicit gates inside `desc x`.
* `Decides F A`: completeness — every yes instance has **some** prover (arbitrary finite
  memory, arbitrary channels) accepted with probability at least `2/3`; soundness — on every no
  instance **every** prover is accepted with probability at most `1/3`.
* `QIP`: promise problems decided by some verifier family.
* `QIPm k`: the same with exactly `k` directed messages in the standard schedule (alternating,
  last to the verifier; `stdSchedule 3 = [P→V, V→P, P→V]`).

Neither class is defined through the other, through an SDP, or through any transformation.
`qipm_subset_qip` proves `QIPm k ⊆ QIP` directly. The converse for `k = 3` is the target of
the plan.
-/

namespace ShiQIP

/-- A promise problem: disjoint yes and no instances. -/
structure PromiseProblem where
  yes : Set Str
  no : Set Str
  disjoint : Disjoint yes no

/-- A language as the promise problem `(L, Lᶜ)`. -/
def ofLanguage (L : Language Bool) : PromiseProblem := ⟨L, Lᶜ, disjoint_compl_right⟩

/-- A polynomial-time uniform, polynomially bounded family of valid verifiers. -/
structure VerifierFamily where
  desc : Str → Desc
  valid : ∀ x, (desc x).Valid
  gen : Str → Str
  gen_polyTime : PvsNP.PolyTimeComputable gen
  gen_eq : ∀ x, gen x = encode (desc x)
  bound : Polynomial ℕ
  msgs_le : ∀ x, (desc x).numMsgs ≤ bound.eval x.length
  wires_le : ∀ x, (desc x).totalWires ≤ bound.eval x.length
  gates_le : ∀ x, (desc x).gateCount ≤ bound.eval x.length

/-- `F` decides `A` with completeness `2/3` and soundness `1/3`. -/
def Decides (F : VerifierFamily) (A : PromiseProblem) : Prop :=
  (∀ x ∈ A.yes, ∃ P : Prover (F.desc x), (2 : ℝ) / 3 ≤ accept P) ∧
    (∀ x ∈ A.no, ∀ P : Prover (F.desc x), accept P ≤ (1 : ℝ) / 3)

/-- **QIP**: promise problems with a polynomial-message quantum interactive proof. -/
def QIP : Set PromiseProblem := {A | ∃ F : VerifierFamily, Decides F A}

/-- **QIP(k)**: as `QIP`, with exactly `k` messages in the standard schedule. -/
def QIPm (k : ℕ) : Set PromiseProblem :=
  {A | ∃ F : VerifierFamily, (∀ x, (F.desc x).HasSchedule k) ∧ Decides F A}

/-- `QIP(k) ⊆ QIP`, without any compression. -/
theorem qipm_subset_qip (k : ℕ) : QIPm k ⊆ QIP := fun _ ⟨F, _, hF⟩ => ⟨F, hF⟩

/-- A `QIPm k` family has exactly `k` messages on every input. -/
theorem numMsgs_of_mem_qipm {k : ℕ} {F : VerifierFamily} (h : ∀ x, (F.desc x).HasSchedule k)
    (x : Str) : (F.desc x).numMsgs = k :=
  Desc.numMsgs_of_hasSchedule (h x)

/-- Yes and no instances of a promise problem are distinct. -/
theorem PromiseProblem.not_yes_and_no (A : PromiseProblem) {x : Str} (hy : x ∈ A.yes)
    (hn : x ∈ A.no) : False :=
  Set.disjoint_left.mp A.disjoint hy hn

end ShiQIP
