import QIP.Uniform.ThreePT
import QIP.Classes


/-!
# Q39 — the transformed verifier family

For a verifier family `F`, `F.three` has descriptions `threeDesc (F.desc x)`:

* valid, with the three-message schedule (`threeDesc_spec`);
* generated by `printer ∘ F.gen`, polynomial-time computable as a composition of two
  polynomial-time computable functions (`polyTime_comp`, `printer_polyTime`), and printing
  exactly `encode (threeDesc (F.desc x))` (`printer_encode`);
* polynomially bounded: messages, wires and gates are at most `hsize (threeDesc (F.desc x))`,
  which `hsize_threeDesc_le` bounds by `C · (hsize (F.desc x) + 1) ^ 14`.

`three_decides`: if `F` decides `A` (completeness `2/3`, soundness `1/3`) so does `F.three`.
-/

open ShiQIP.Uniform ShiQIP.Arith

namespace ShiQIP

/-- The constant of `hsize_threeDesc_le`. -/
def threeC : ℕ := 38 * 72 * 189 ^ 2 * 94 ^ 11 * 465

/-- The resource bound of the transformed family. -/
noncomputable def threeBound (p : Polynomial ℕ) : Polynomial ℕ :=
  Polynomial.C threeC * (3 * p + 2) ^ 14

theorem hsize_three_le (F : VerifierFamily) (x : Str) :
    hsize (threeDesc (F.desc x)) ≤ (threeBound F.bound).eval x.length := by
  have h := hsize_threeDesc_le (F.valid x)
  have hm := F.msgs_le x
  have hw := F.wires_le x
  have hg := F.gates_le x
  have hs : hsize (F.desc x) + 1 ≤ 3 * F.bound.eval x.length + 2 := by unfold hsize; omega
  have := Nat.pow_le_pow_left hs 14
  simp only [threeBound, threeC, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow,
    Polynomial.eval_add, Polynomial.eval_ofNat]
  exact h.trans (Nat.mul_le_mul_left _ this)

/-- **The transformed family.** -/
noncomputable def VerifierFamily.three (F : VerifierFamily) : VerifierFamily where
  desc x := threeDesc (F.desc x)
  valid x := (threeDesc_spec (F.valid x)).1
  gen := printer ∘ F.gen
  gen_polyTime := TMComp.polyTime_comp F.gen_polyTime printer_polyTime
  gen_eq x := by simp only [Function.comp_apply, F.gen_eq, printer_encode (F.valid x)]
  bound := threeBound F.bound
  msgs_le x := le_trans (by unfold hsize; omega) (hsize_three_le F x)
  wires_le x := le_trans (by unfold hsize; omega) (hsize_three_le F x)
  gates_le x := le_trans (by unfold hsize; omega) (hsize_three_le F x)

theorem VerifierFamily.three_schedule (F : VerifierFamily) (x : Str) :
    (F.three.desc x).HasSchedule 3 := (threeDesc_spec (F.valid x)).2.1

/-- **The transformed family decides the same promise problem.** -/
theorem VerifierFamily.three_decides {F : VerifierFamily} {A : PromiseProblem} (h : Decides F A) :
    Decides F.three A := by
  refine ⟨fun x hx => ?_, fun x hx => ?_⟩
  · have hv : (2 : ℝ) / 3 ≤ value (F.desc x) := (le_value_iff _ _).mp (h.1 x hx)
    have h1 := (threeDesc_spec (F.valid x)).2.2.1 hv
    exact (le_value_iff (threeDesc (F.desc x)) (2 / 3)).mpr (by rw [h1]; norm_num)
  · have hv : value (F.desc x) ≤ (1 : ℝ) / 3 := (value_le_iff _ _).mp (h.2 x hx)
    exact (value_le_iff (threeDesc (F.desc x)) (1 / 3)).mpr ((threeDesc_spec (F.valid x)).2.2.2 hv)

end ShiQIP
