/-
Copyright (c) 2026 Yueheng Shi. All rights reserved.
Released under the Apache License, Version 2.0.
Authors: Yueheng Shi

Bounded-error quantum circuit classes -- DEFINITIONS ONLY.

Built against Mathlib (Apache-2.0) at revision 0df444a360eaa60ab8c11dca51a86af692955474.
-/
import Definitions.Def_ShiShallow_Core

set_option autoImplicit false

/-!
# Bounded-error quantum circuit families and the classes they decide

This bundle provides the scaffolding for statements of the form "this language is decided by
a quantum circuit family with bounded error": languages as length-indexed predicates on bit
strings, circuit families with ancillas and a designated output wire, the acceptance
probability of a family on an input, bounded-error decision with explicit thresholds, a
depth bound, and the complement constructions on both languages and families.

## THIS IS NOT A FORMALISATION OF BQP

`BQP` requires the circuit family to be UNIFORM -- generated by a classical polynomial-time
machine. No machine model is used anywhere in this bundle, and no uniformity condition is
defined. Instead `InClass` takes the uniformity condition as an explicit PARAMETER `U`, a
predicate on families supplied by the caller, and likewise takes the resource bound as a
parameter. So:

* `InClass U bound lo hi L` is read as "L is decided with error thresholds `lo`/`hi` by some
  family satisfying `U` whose depth is bounded by some `p` satisfying `bound`";
* instantiating `U := fun _ => True` drops the uniformity requirement entirely, leaving a
  class determined by `bound` and the thresholds alone. How large that class is depends on
  `bound` as well: with an unrestrictive `bound` the family is unconstrained data and nothing
  ties it to any computation. No containment or separation between instantiations is proved
  here, and none should be read in;
* recovering `BQP` itself would require instantiating `U` with a genuine poly-time-uniformity
  predicate, which this bundle does NOT provide and does not claim to.

Every theorem proved against these definitions is therefore a statement about `InClass U ...`
for the `U` it quantifies over, NOT about `BQP`. Names should say so.

## Conventions INHERITED from `Def_ShiShallow_Core`, not established here

`acceptProb`, `depth`, `Bits`, `Layered` and `Instr.x` all come from the imported bundle, and
this file proves nothing about them. In particular it is that bundle, not this one, that
fixes: that `acceptProb` is the probability of the output wire reading `1` (rather than `0`)
with ancillas initialised to zero; that it lies in `[0,1]` -- no such bound is available here,
so every threshold statement below is only as meaningful as that external fact; that `depth`
counts layers rather than gates; and that `Instr.x` is a bit flip. The negative claims in this
docstring are about THIS FILE.

## Other deliberate limitations

* The resource bound is on `ShiShallow.depth` only. Nothing here bounds circuit SIZE, gate
  count, or ancilla count, and nothing forces `p` to be a polynomial -- `bound` is an
  arbitrary predicate on `ℕ → ℕ`.
* Thresholds are explicit parameters `lo hi : ℝ`. Nothing requires `lo < hi`, nothing
  requires them to be `1/3` and `2/3`, and no amplification or error-reduction result is
  proved or even stated.
* `Language` is `(n : ℕ) → Bits n → Prop`, i.e. a `Prop`-valued predicate per length. It
  carries no decidability and no computability condition whatsoever.
* DEFINITIONS ONLY: no theorem is WRITTEN in this file. (Declaring `structure Family` does
  generate the usual auxiliary lemmas -- injectivity of the constructor and the like -- so
  the environment is not literally theorem-free; nothing mathematical is proved.) In
  particular nothing here proves that `negate` flips the acceptance probability, that any
  class is closed under complement, union or intersection, or any relation between two
  instantiations of `U`.
-/

namespace ShiClass

open ShiShallow

/-- A language, as a predicate on bit strings indexed by input length. Carries no
decidability or computability condition. -/
def Language := (n : ℕ) → Bits n → Prop

/-- The complement of a language, pointwise negation. -/
def Language.compl (L : Language) : Language := fun n x => ¬ L n x

/-- A quantum circuit family: for each input length `n`, a number of ancilla wires, a
layered circuit on `n + anc n` wires, and a designated output wire. The family is plain
DATA -- no uniformity or computability condition is imposed here. -/
structure Family where
  /-- Number of ancilla wires at input length `n`, BEYOND a mandatory first one: the circuit
  at length `n` acts on `n + (anc n + 1)` wires. The `+ 1` is what makes the output wire
  always exist -- with a bare `anc n` the field `out 0 : Fin (0 + anc 0)` would force every
  family to satisfy `anc 0 ≥ 1`, silently outlawing ancilla-free behaviour at length `0`. -/
  anc : ℕ → ℕ
  /-- The circuit at input length `n`, acting on the `n` input wires followed by `anc n + 1`
  ancilla wires. -/
  circ : (n : ℕ) → Layered (n + (anc n + 1))
  /-- The wire whose measurement is the output, at input length `n`. Always exists, since
  `n + (anc n + 1) ≥ 1`. -/
  out : (n : ℕ) → Fin (n + (anc n + 1))

/-- The acceptance probability of the family on input `x`, i.e. the probability that the
designated output wire reads `1` after running the circuit on `x` padded with zero
ancillas. -/
noncomputable def Family.accept (F : Family) (n : ℕ) (x : Bits n) : ℝ :=
  acceptProb (F.circ n) x (F.out n)

/-- `F` decides `L` with error thresholds `lo` and `hi`: members of `L` are accepted with
probability at least `hi`, non-members with probability at most `lo`. Nothing requires
`lo < hi`, so this predicate does NOT by itself express a bounded-error gap. Note the
degenerate regime is subtler than it looks: `lo = hi = c` demands acceptance EXACTLY `c` on
every input, which need not be achievable at all by circuits over this gate set, so no claim
is made here about which threshold pairs are satisfiable. -/
def Family.Decides (F : Family) (L : Language) (lo hi : ℝ) : Prop :=
  ∀ (n : ℕ) (x : Bits n), (L n x → hi ≤ F.accept n x) ∧ (¬ L n x → F.accept n x ≤ lo)

/-- The family's depth is bounded by `p` at every input length. This bounds DEPTH only:
not size, not gate count, not ancilla count. -/
def Family.DepthBounded (F : Family) (p : ℕ → ℕ) : Prop :=
  ∀ n : ℕ, depth (F.circ n) ≤ p n

/-- Appending a single `X` gate on the output wire.

If `F` decides `L` with thresholds `lo`/`hi`, this construction decides `L.compl` with the
REFLECTED pair `1 - hi` / `1 - lo` -- not with `lo`/`hi`. NO property of it is proved in this
file, including that it flips the acceptance probability at all. -/
def Family.negate (F : Family) : Family where
  anc := F.anc
  circ := fun n => F.circ n ++ [[Instr.x (F.out n)]]
  out := F.out

/-- `L` is decided with thresholds `lo`/`hi` by some family satisfying the uniformity
predicate `U`, with depth bounded by some `p` satisfying `bound`.

`U` and `bound` are PARAMETERS, not definitions: this is deliberately not `BQP`. See the
module docstring -- instantiating `U := fun _ => True` gives the non-uniform class, and no
poly-time-uniformity predicate is provided anywhere in this bundle. -/
def InClass (U : Family → Prop) (bound : (ℕ → ℕ) → Prop) (lo hi : ℝ) (L : Language) : Prop :=
  ∃ (F : Family) (p : ℕ → ℕ), U F ∧ bound p ∧ F.DepthBounded p ∧ F.Decides L lo hi

end ShiClass
