import Definitions.Def_ShiClassPP
import Lean
import Lean.Util.CollectAxioms
import Lean.Util.FoldConsts
import Theorems.Thm_ShiClassPP_patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality

namespace BQPReferenceValidation.Source25
/-
Copyright (c) 2026 Yueheng Shi. All rights reserved.
Released under the Apache License, Version 2.0.
Authors: Yueheng Shi
-/

set_option autoImplicit false
set_option maxHeartbeats 1600000

/-! SHORT-MACH.  THE INSTANCE-CONDITIONAL BRANCH: A POLYNOMIAL-TIME CHECKER PATCHED TO
CONSTANTS ON THE THREE INSTANCES OF LENGTH AT MOST ONE IS STILL A POLYNOMIAL-TIME CHECKER.

`ShiClassPP.PP` hard-codes the witness length as `x.length ^ k`, so the three instances
`[]`, `[false]`, `[true]` have to be settled by hand (see `SHORT-COUNT`).  The counting half
is done there; this is the MACHINE half: the patched checker must still be polynomial time.

WHAT IS PROVED HERE, AND WHAT IS NOT.  The accepted closure kit for `PvsNP.PolyTimeChecker`
contains complement closure, witness truncation and symbolwise preprocessing, and nothing
else.  Every one of those three produces a checker of the form `R ∘ T` or `!(R ∘ T)`, so the
kit is closed under the two-element group generated by output negation and cannot reach a
constant: no composite of preprocessing with output relabelling, applied to an arbitrary
`R`, is constant on a nonempty set of instances.  The genuinely new primitive needed is a
BINARY combination of two checkers, and exactly one is taken as a hypothesis:

* `hAnd` -- `PolyTimeChecker` is closed under `&&`.

Everything else is either an accepted platform theorem taken as a hypothesis in its accepted
form (`hNeg`: complement closure, `BRIDGE-Cb` (8) /
`PvsNP.polyTime_composition_and_alphabet_transport` (8); `hProj`: the instance projection
bridge, `TRANSDUCE-1c` (6) / `PvsNP.tagged_transducers_untaggers_and_projections` (6)), or
proved below.  One further hypothesis,

* `hEqDec` -- for a FIXED string `a`, `fun w => decide (w = a)` is a polynomial-time decider,

is a bounded-lookahead machine obligation of the same kind as the accepted concrete
checkers, and is not the conceptual content of this slice.

STRUCTURE OF THE ARGUMENT.
* (1) `&&` plus complement gives `||`.
* (2) the instance-equality selector `fun p => decide (p.1 = a)` is a polynomial-time
  checker, by the projection bridge.
* (3) THE BRANCH COMBINATOR, by cases on the constant: at `true` the patch is `sel || R`, at
  `false` it is `!sel && R`.  This is what the accepted kit does not have.
* (4) THE TARGET, as three nested applications of (3) at `[true]`, `[false]`, `[]` -- in that
  order, so that the outermost test wins.
* (5)-(6) the patched checker's defining values: constant in the witness on each short
  instance, and EQUAL TO `R` on every instance of length at least two.
* (7) hence the two checkers have the same `countAccept` at every long instance, which lets
  a consumer state its long-input correctness hypothesis for the ORIGINAL `R`.
* (8) THE WELD to `SHORT-COUNT` (7), whose hypothesis shape (4)-(6) reproduce exactly.

HONEST LIMITATIONS.
1. `hAnd` is UNDISCHARGED and is the whole machine content of the branch.  It is not
   derivable from the accepted kit: `Turing.haltList` pins every non-output stack of a
   halted `FinTM2` to empty, so nothing survives a black-box checker call except its one
   output symbol, and sequential composition (`ShiTM2.comp`) therefore cannot recombine that
   symbol with any property of the original input.  A conditional composite is new machine
   DATA, not a corollary of the accepted theorems.
2. `hEqDec` is undischarged; it is a concrete bounded-lookahead machine, not a closure
   property.
3. Nothing quantum appears; `R` is an arbitrary Boolean checking relation.
4. `k ≥ 1` is inherited from `SHORT-COUNT` (7) and is not weakened here.
-/

open PvsNP ShiClassPP

/-! ### The patched checker -/

/-- The checker `R` patched to the constants `c₀`, `c₁`, `c₂` on the three instances of
length at most one. -/
private def patch (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) : Str × Str → Bool :=
  fun p => if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
    if p.1 = [true] then c₂ else R p

/-! ### (1) Disjunction from conjunction and complement -/

private lemma orClosure
    (hNeg : ∀ R : Str × Str → Bool, PolyTimeChecker R →
      PolyTimeChecker (fun p => !(R p)))
    (hAnd : ∀ R S : Str × Str → Bool, PolyTimeChecker R → PolyTimeChecker S →
      PolyTimeChecker (fun p => R p && S p))
    (R S : Str × Str → Bool) (hR : PolyTimeChecker R) (hS : PolyTimeChecker S) :
    PolyTimeChecker (fun p => R p || S p) := by
  have he : (fun p : Str × Str => R p || S p)
      = fun p : Str × Str => !((!(R p)) && (!(S p))) := by
    funext p
    cases h1 : R p <;> cases h2 : S p <;> rfl
  rw [he]
  exact hNeg _ (hAnd _ _ (hNeg R hR) (hNeg S hS))

/-! ### (2) The instance-equality selector -/

private lemma selChecker
    (hProj : ∀ χ : Str → Bool, PolyTimeDecider χ →
      PolyTimeChecker (fun p : Str × Str => χ p.1))
    (hEqDec : ∀ a : Str, PolyTimeDecider (fun w : Str => decide (w = a)))
    (a : Str) : PolyTimeChecker (fun p : Str × Str => decide (p.1 = a)) :=
  hProj (fun w : Str => decide (w = a)) (hEqDec a)

/-! ### (3) The branch combinator -/

private lemma patchOne
    (hNeg : ∀ R : Str × Str → Bool, PolyTimeChecker R →
      PolyTimeChecker (fun p => !(R p)))
    (hAnd : ∀ R S : Str × Str → Bool, PolyTimeChecker R → PolyTimeChecker S →
      PolyTimeChecker (fun p => R p && S p))
    (hProj : ∀ χ : Str → Bool, PolyTimeDecider χ →
      PolyTimeChecker (fun p : Str × Str => χ p.1))
    (hEqDec : ∀ a : Str, PolyTimeDecider (fun w : Str => decide (w = a)))
    (R : Str × Str → Bool) (a : Str) (c : Bool) (hR : PolyTimeChecker R) :
    PolyTimeChecker (fun p : Str × Str => if p.1 = a then c else R p) := by
  have hS := selChecker hProj hEqDec a
  cases c with
  | true =>
      have he : (fun p : Str × Str => if p.1 = a then true else R p)
          = fun p : Str × Str => decide (p.1 = a) || R p := by
        funext p
        by_cases hp : p.1 = a <;> simp [hp]
      rw [he]
      exact orClosure hNeg hAnd _ _ hS hR
  | false =>
      have he : (fun p : Str × Str => if p.1 = a then false else R p)
          = fun p : Str × Str => (!(decide (p.1 = a))) && R p := by
        funext p
        by_cases hp : p.1 = a <;> simp [hp]
      rw [he]
      exact hAnd _ _ (hNeg _ hS) hR

/-! ### (4) The three-instance patch -/

private lemma patchThree
    (hNeg : ∀ R : Str × Str → Bool, PolyTimeChecker R →
      PolyTimeChecker (fun p => !(R p)))
    (hAnd : ∀ R S : Str × Str → Bool, PolyTimeChecker R → PolyTimeChecker S →
      PolyTimeChecker (fun p => R p && S p))
    (hProj : ∀ χ : Str → Bool, PolyTimeDecider χ →
      PolyTimeChecker (fun p : Str × Str => χ p.1))
    (hEqDec : ∀ a : Str, PolyTimeDecider (fun w : Str => decide (w = a)))
    (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (hR : PolyTimeChecker R) :
    PolyTimeChecker (fun p : Str × Str =>
      if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
        if p.1 = [true] then c₂ else R p) := by
  have h2 := patchOne hNeg hAnd hProj hEqDec R [true] c₂ hR
  have h1 := patchOne hNeg hAnd hProj hEqDec _ [false] c₁ h2
  exact patchOne hNeg hAnd hProj hEqDec _ [] c₀ h1

/-! ### (5)-(6) The patched checker's defining values -/

private lemma patchNil (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (w : Str) :
    patch R c₀ c₁ c₂ ([], w) = c₀ := by
  simp [patch]

private lemma patchFalse (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (w : Str) :
    patch R c₀ c₁ c₂ ([false], w) = c₁ := by
  simp [patch]

private lemma patchTrue (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (w : Str) :
    patch R c₀ c₁ c₂ ([true], w) = c₂ := by
  simp [patch]

private lemma patchLong (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (x w : Str)
    (hx : 2 ≤ x.length) : patch R c₀ c₁ c₂ (x, w) = R (x, w) := by
  have h0 : x ≠ [] := by
    intro h
    rw [h] at hx
    simp at hx
  have h1 : x ≠ [false] := by
    intro h
    rw [h] at hx
    simp at hx
  have h2 : x ≠ [true] := by
    intro h
    rw [h] at hx
    simp at hx
  simp [patch, h0, h1, h2]

/-! ### (7) The counts agree at every long instance -/

private lemma caCongr (R S : Str × Str → Bool) (x : Str) (m : ℕ)
    (h : ∀ w : Str, R (x, w) = S (x, w)) :
    countAccept R x m = countAccept S x m := by
  simp only [countAccept, h]

private lemma patchCount (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (x : Str) (m : ℕ)
    (hx : 2 ≤ x.length) :
    countAccept (patch R c₀ c₁ c₂) x m = countAccept R x m :=
  caCongr _ _ x m (fun w => patchLong R c₀ c₁ c₂ x w hx)

theorem _root_.BQPReferenceValidation.candidate25
    -- ACCEPTED: complement closure (`BRIDGE-Cb` (8)).
    (hNeg : ∀ R : Str × Str → Bool, PolyTimeChecker R →
      PolyTimeChecker (fun p => !(R p)))
    -- ACCEPTED: the instance projection bridge (`TRANSDUCE-1c` (6)).
    (hProj : ∀ χ : Str → Bool, PolyTimeDecider χ →
      PolyTimeChecker (fun p : Str × Str => χ p.1))
    -- NEW MACHINE OBLIGATION, the whole content of the branch: `PolyTimeChecker` is closed
    -- under `&&`.  NOT derivable from the accepted kit, which only produces `R ∘ T` and
    -- `!(R ∘ T)` and can therefore never reach a constant.
    (hAnd : ∀ R S : Str × Str → Bool, PolyTimeChecker R → PolyTimeChecker S →
      PolyTimeChecker (fun p => R p && S p))
    -- NEW, but a concrete bounded-lookahead machine, not a closure property.
    (hEqDec : ∀ a : Str, PolyTimeDecider (fun w : Str => decide (w = a))) :
    -- (1) DISJUNCTION, from `&&` and complement.
    (∀ R S : Str × Str → Bool, PolyTimeChecker R → PolyTimeChecker S →
        PolyTimeChecker (fun p => R p || S p))
    -- (2) THE INSTANCE-EQUALITY SELECTOR is a polynomial-time checker.
  ∧ (∀ a : Str, PolyTimeChecker (fun p : Str × Str => decide (p.1 = a)))
    -- (3) THE BRANCH COMBINATOR: a checker patched to a CONSTANT on ONE instance is still a
    -- polynomial-time checker.
  ∧ (∀ (R : Str × Str → Bool) (a : Str) (c : Bool), PolyTimeChecker R →
        PolyTimeChecker (fun p : Str × Str => if p.1 = a then c else R p))
    -- (4) THE TARGET: patched to constants on ALL THREE instances of length at most one.
  ∧ (∀ (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool), PolyTimeChecker R →
        PolyTimeChecker (fun p : Str × Str =>
          if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
            if p.1 = [true] then c₂ else R p))
    -- (5) THE PATCHED CHECKER IS CONSTANT IN THE WITNESS on each short instance -- exactly
    -- the three hypotheses `SHORT-COUNT` (7) asks for.
  ∧ (∀ (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool),
        (∀ w : Str, (fun p : Str × Str =>
            if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
              if p.1 = [true] then c₂ else R p) ([], w) = c₀)
      ∧ (∀ w : Str, (fun p : Str × Str =>
            if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
              if p.1 = [true] then c₂ else R p) ([false], w) = c₁)
      ∧ (∀ w : Str, (fun p : Str × Str =>
            if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
              if p.1 = [true] then c₂ else R p) ([true], w) = c₂))
    -- (6) AND IT IS `R` ITSELF on every instance of length at least two: the patch is
    -- invisible exactly where the counting argument lives.
  ∧ (∀ (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (x w : Str), 2 ≤ x.length →
        (fun p : Str × Str =>
          if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
            if p.1 = [true] then c₂ else R p) (x, w) = R (x, w))
    -- (7) HENCE THE COUNTS AGREE at every long instance and every witness length.
  ∧ (∀ (R : Str × Str → Bool) (c₀ c₁ c₂ : Bool) (x : Str) (m : ℕ), 2 ≤ x.length →
        countAccept (fun p : Str × Str =>
          if p.1 = [] then c₀ else if p.1 = [false] then c₁ else
            if p.1 = [true] then c₂ else R p) x m = countAccept R x m)
    -- (8) THE WELD TO `SHORT-COUNT` (7), taken as a hypothesis here since it is an accepted
    -- theorem.  Note what is left for the consumer: long-input correctness of the ORIGINAL
    -- `R`, and the three membership equivalences.  No polynomial-time hypothesis on the
    -- patched checker survives.
  ∧ (∀ (L : Language Bool) (R : Str × Str → Bool) (k : ℕ) (c₀ c₁ c₂ : Bool),
        (∀ (L' : Language Bool) (R' : Str × Str → Bool) (k' : ℕ) (d₀ d₁ d₂ : Bool),
            1 ≤ k' → PolyTimeChecker R' →
            (∀ x : Str, 2 ≤ x.length →
              (x ∈ L' ↔ 2 * countAccept R' x (x.length ^ k') > 2 ^ (x.length ^ k'))) →
            (∀ w : Str, R' ([], w) = d₀) → (∀ w : Str, R' ([false], w) = d₁) →
            (∀ w : Str, R' ([true], w) = d₂) →
            (d₀ = true ↔ [] ∈ L') → (d₁ = true ↔ [false] ∈ L') →
            (d₂ = true ↔ [true] ∈ L') →
            L' ∈ PP) →
        1 ≤ k → PolyTimeChecker R →
        (∀ x : Str, 2 ≤ x.length →
          (x ∈ L ↔ 2 * countAccept R x (x.length ^ k) > 2 ^ (x.length ^ k))) →
        (c₀ = true ↔ [] ∈ L) → (c₁ = true ↔ [false] ∈ L) → (c₂ = true ↔ [true] ∈ L) →
        L ∈ PP)
    -- (9) NON-VACUITY: the patch really does change values.  At the concrete seed
    -- `fun p => (p.1 ++ p.2).headI`, which accepts `([], [true])` and `([true], [])`, the
    -- patch to `false, false, false` rejects BOTH, while a length-two instance is untouched.
  ∧ ((fun p : Str × Str => (p.1 ++ p.2).headI) ([], [true]) = true
      ∧ (fun p : Str × Str => (p.1 ++ p.2).headI) ([true], []) = true
      ∧ (fun p : Str × Str =>
          if p.1 = [] then false else if p.1 = [false] then false else
            if p.1 = [true] then false else (p.1 ++ p.2).headI) ([], [true]) = false
      ∧ (fun p : Str × Str =>
          if p.1 = [] then false else if p.1 = [false] then false else
            if p.1 = [true] then false else (p.1 ++ p.2).headI) ([true], []) = false
      ∧ (fun p : Str × Str =>
          if p.1 = [] then false else if p.1 = [false] then false else
            if p.1 = [true] then false else (p.1 ++ p.2).headI)
              ([true, false], []) = true) := by
  refine ⟨fun R S hR hS => orClosure hNeg hAnd R S hR hS,
    fun a => selChecker hProj hEqDec a,
    fun R a c hR => patchOne hNeg hAnd hProj hEqDec R a c hR,
    fun R c₀ c₁ c₂ hR => patchThree hNeg hAnd hProj hEqDec R c₀ c₁ c₂ hR,
    fun R c₀ c₁ c₂ => ⟨fun w => patchNil R c₀ c₁ c₂ w, fun w => patchFalse R c₀ c₁ c₂ w,
      fun w => patchTrue R c₀ c₁ c₂ w⟩,
    fun R c₀ c₁ c₂ x w hx => patchLong R c₀ c₁ c₂ x w hx,
    fun R c₀ c₁ c₂ x m hx => patchCount R c₀ c₁ c₂ x m hx, ?_,
    by decide, by decide, by decide, by decide, by decide⟩
  intro L R k c₀ c₁ c₂ hSC7 hk hR hlong e0 e1 e2
  refine hSC7 L (patch R c₀ c₁ c₂) k c₀ c₁ c₂ hk
    (patchThree hNeg hAnd hProj hEqDec R c₀ c₁ c₂ hR) ?_
    (fun w => patchNil R c₀ c₁ c₂ w) (fun w => patchFalse R c₀ c₁ c₂ w)
    (fun w => patchTrue R c₀ c₁ c₂ w) e0 e1 e2
  intro x hx
  rw [patchCount R c₀ c₁ c₂ x (x.length ^ k) hx]
  exact hlong x hx

end BQPReferenceValidation.Source25

open Lean Elab Command Meta in
run_cmd do
  liftTermElabM do
    let info ← getConstInfo ``BQPReferenceValidation.candidate25
    let target ← getConstInfo ``ShiClassPP.patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality
    unless info.levelParams.length == target.levelParams.length do
      throwError "Universe parameter mismatch: ShiClassPP.patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality"
    let proofType := info.type.instantiateLevelParams info.levelParams
      (target.levelParams.map Level.param)
    unless ← isDefEq proofType target.type do
      throwError "Proof type mismatch: ShiClassPP.patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality"
    if (info.value? (allowOpaque := true)).any (fun v => v.getUsedConstants.contains ``sorryAx) then
      throwError "Direct placeholder: ShiClassPP.patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality"
    let axioms ← collectAxioms ``BQPReferenceValidation.candidate25
    logInfo m!"BQP_REFERENCE_TYPE_CHECKED ShiClassPP.patching_a_polynomial_time_checker_to_constants_on_the_three_shortest_instances_from_conjunction_and_equality; axioms {axioms}"
