import QIP.Bell.Honest

/-! Fresh-import audit for the Q27 Bell-test core: statement types, then transitive axioms. -/

open ShiQIP ShiQuantum Matrix

#check (value_bellDesc_le : ∀ {d : Desc}, d.Valid → value d ≤ 1 / 3 → value (bellDesc d) ≤ 35 / 36)
#check (exists_iso_accept_one : ∀ {d : Desc}, d.Valid →
  ∀ (T₀ : IsoStrategy (Reg d) (Reg d) d.numMsgs), accept T₀.toOp = 1 / 2 →
    ∃ T : IsoStrategy (Reg (bellDesc d)) (Reg (bellDesc d)) (bellDesc d).numMsgs,
      accept T.toOp = 1)

#print axioms ShiQIP.reduceTo
#print axioms ShiQIP.localOp
#print axioms ShiQIP.splitMem
#print axioms ShiQIP.localOp_eq
#print axioms ShiQIP.reduceTo_eq
#print axioms ShiQIP.trace_localOp_mul
#print axioms ShiQIP.reduceTo_ext
#print axioms ShiQIP.restOp
#print axioms ShiQIP.localOp_turn
#print axioms ShiQIP.trace_submatrix_mul
#print axioms ShiQIP.reduceTo_proverStep
#print axioms ShiQIP.Z00
#print axioms ShiQIP.Z0
#print axioms ShiQIP.bellPr
#print axioms ShiQIP.margB
#print axioms ShiQIP.re_mul_star_half
#print axioms ShiQIP.trace_bell_pureState
#print axioms ShiQIP.splitO
#print axioms ShiQIP.bellPr_le
#print axioms ShiQIP.wire1
#print axioms ShiQIP.outsideZ0
#print axioms ShiQIP.embSplit_wire1_symm
#print axioms ShiQIP.margB_eq_reduceTo
#print axioms ShiQIP.priv_le_totalWires
#print axioms ShiQIP.wB
#print axioms ShiQIP.wOut
#print axioms ShiQIP.wO
#print axioms ShiQIP.wO_ne_wB
#print axioms ShiQIP.wO_ne_wOut
#print axioms ShiQIP.wB_ne_wOut
#print axioms ShiQIP.finalInstrs
#print axioms ShiQIP.blockMat_bell_final
#print axioms ShiQIP.update_update_comm
#print axioms ShiQIP.run4_apply
#print axioms ShiQIP.runFinal_apply
#print axioms ShiQIP.zero3
#print axioms ShiQIP.norm_half_add
#print axioms ShiQIP.final_term
#print axioms ShiQIP.acceptSum_final
#print axioms ShiQIP.kron_one_mulVec_apply
#print axioms ShiQIP.outBit_bell
#print axioms ShiQIP.re_star_mul_self
#print axioms ShiQIP.accept_expect_bell
#print axioms ShiQIP.bellShift_lt_msgOff
#print axioms ShiQIP.sw
#print axioms ShiQIP.mw
#print axioms ShiQIP.sw_val
#print axioms ShiQIP.mw_val
#print axioms ShiQIP.sw_ne_mw
#print axioms ShiQIP.sw_inj
#print axioms ShiQIP.mw_inj
#print axioms ShiQIP.σ
#print axioms ShiQIP.σ_sw
#print axioms ShiQIP.σ_mw
#print axioms ShiQIP.σ_fix
#print axioms ShiQIP.swapsUpTo
#print axioms ShiQIP.runLayer_swapsUpTo
#print axioms ShiQIP.out_lt_W
#print axioms ShiQIP.sw_out_ne_wB
#print axioms ShiQIP.bellG_eq
#print axioms ShiQIP.bellG_mulVec
#print axioms ShiQIP.not_inReg_of_lt_priv
#print axioms ShiQIP.turnSplit_symm_fst
#print axioms ShiQIP.one_kron_mulVec_apply
#print axioms ShiQIP.turnVec_vanish
#print axioms ShiQIP.margB_turnVec
#print axioms ShiQIP.accept_expect
#print axioms ShiQIP.sum_norm_pureRun
#print axioms ShiQIP.wB_ne_sw
#print axioms ShiQIP.wOut_ne_sw
#print axioms ShiQIP.wB_ne_mw
#print axioms ShiQIP.wOut_ne_mw
#print axioms ShiQIP.σ_wB
#print axioms ShiQIP.σ_wOut
#print axioms ShiQIP.wB_not_mem
#print axioms ShiQIP.wOut_not_mem
#print axioms ShiQIP.pureRun_bell_apply
#print axioms ShiQIP.embV_eq_zero
#print axioms ShiQIP.pureRun_bell_wOut
#print axioms ShiQIP.mul_star_eq_norm_sq
#print axioms ShiQIP.σ_symm_mw_out
#print axioms ShiQIP.σ_symm_wB
#print axioms ShiQIP.pureRun_bell_update
#print axioms ShiQIP.pBell
#print axioms ShiQIP.embSplit_symm_emb
#print axioms ShiQIP.embSplit_symm_out
#print axioms ShiQIP.margB_bell
#print axioms ShiQIP.blockMat_bell_mid
#print axioms ShiQIP.not_inReg_wB
#print axioms ShiQIP.not_inReg_wOut
#print axioms ShiQIP.outBit_iff
#print axioms ShiQIP.accept_restrict
#print axioms ShiQIP.accept_bell_le
#print axioms ShiQIP.value_bellDesc_le
#print axioms ShiQIP.turnVec_relabel
#print axioms ShiQIP.pureRun_relabel
#print axioms ShiQIP.accept_relabel
#print axioms ShiQIP.msgOffset_bell_m
#print axioms ShiQIP.msgWidth_bell_m
#print axioms ShiQIP.msgOffset_bell_m1
#print axioms ShiQIP.msgWidth_bell_m1
#print axioms ShiQIP.inReg_bell_m
#print axioms ShiQIP.inReg_bell_m1
#print axioms ShiQIP.inReg_mw
#print axioms ShiQIP.wire_cases
#print axioms ShiQIP.StoreT
#print axioms ShiQIP.hMem
#print axioms ShiQIP.hMem.fintype
#print axioms ShiQIP.hMem.decEq
#print axioms ShiQIP.eM
#print axioms ShiQIP.eA
#print axioms ShiQIP.eB
#print axioms ShiQIP.iso_submatrix_equiv
#print axioms ShiQIP.hVA
#print axioms ShiQIP.hVA_iso
#print axioms ShiQIP.hVstore
#print axioms ShiQIP.hVstore_iso
#print axioms ShiQIP.oVal
#print axioms ShiQIP.reg_m1_ext
#print axioms ShiQIP.hWfin
#print axioms ShiQIP.regBool
#print axioms ShiQIP.pe
#print axioms ShiQIP.oVal_pe_symm
#print axioms ShiQIP.eB_pe_symm
#print axioms ShiQIP.hWfin_iso
#print axioms ShiQIP.isDensity_pureState_comp
#print axioms ShiQIP.hT
#print axioms ShiQIP.hT_V_lt
#print axioms ShiQIP.hT_V_m
#print axioms ShiQIP.hT_V_m1
#print axioms ShiQIP.pureRun_hT_congr
#print axioms ShiQIP.pBell_hT
#print axioms ShiQIP.wO_ne_sw
#print axioms ShiQIP.wO_ne_mw
#print axioms ShiQIP.σ_wO
#print axioms ShiQIP.wO_not_mem
#print axioms ShiQIP.mw_not_mem
#print axioms ShiQIP.not_inReg_sw
#print axioms ShiQIP.not_inReg_wO
#print axioms ShiQIP.pureRun_bell_sw
#print axioms ShiQIP.pureRun_bell_wO
#print axioms ShiQIP.pureRun_bell_succ
#print axioms ShiQIP.accept_eq_bellPr
#print axioms ShiQIP.hT_V_m_apply
#print axioms ShiQIP.hT_vanish_reg
#print axioms ShiQIP.hT_support
#print axioms ShiQIP.preT
#print axioms ShiQIP.zeroQ
#print axioms ShiQIP.χB
#print axioms ShiQIP.exists_ne_of_ne_zero
#print axioms ShiQIP.margB_preT
#print axioms ShiQIP.isPurification_χB
#print axioms ShiQIP.nonempty_hMem
#print axioms ShiQIP.regSet_regBool
#print axioms ShiQIP.hT_V_m1_apply
#print axioms ShiQIP.hT_last
#print axioms ShiQIP.exists_iso_accept_one
