import QIP.Halve.Run

/-! Fresh-import audit for the Q31 halving soundness: statement types, then transitive axioms. -/

open ShiQIP

#check (value_halve_le : ∀ {d : Desc} {n : ℕ}, d.Valid → 1 ≤ n → n % 2 = 0 → d.numMsgs = 2 * n + 1 →
  value (halveDesc d n) ≤ (1 + Real.sqrt (value d)) / 2)

#print axioms ShiQIP.pmat_mulVec
#print axioms ShiQIP.pmat_mem
#print axioms ShiQIP.turnOp_mulVec
#print axioms ShiQIP.exists_turn_perm
#print axioms ShiQIP.exists_turn_mem
#print axioms ShiQIP.exists_turn_mul
#print axioms ShiQIP.exists_turn_id
#print axioms ShiQIP.not_kept_of_inReg
#print axioms ShiQIP.hPriv_le_total
#print axioms ShiQIP.W_lt_total
#print axioms ShiQIP.workEmb
#print axioms ShiQIP.coinW
#print axioms ShiQIP.outW
#print axioms ShiQIP.caW
#print axioms ShiQIP.MB
#print axioms ShiQIP.workPart
#print axioms ShiQIP.msgPart
#print axioms ShiQIP.ctlOK
#print axioms ShiQIP.Φ
#print axioms ShiQIP.mem_range_workEmb
#print axioms ShiQIP.slice_nonwork
#print axioms ShiQIP.slice_work
#print axioms ShiQIP.slice_ctlOK
#print axioms ShiQIP.slice_msgPart
#print axioms ShiQIP.runLayer_work
#print axioms ShiQIP.flipW
#print axioms ShiQIP.flipW_flipW
#print axioms ShiQIP.runLayer_flip
#print axioms ShiQIP.runLayer_x_apply
#print axioms ShiQIP.runLayer_onF
#print axioms ShiQIP.swR
#print axioms ShiQIP.val_swR
#print axioms ShiQIP.swapRange
#print axioms ShiQIP.runLayer_swapRange
#print axioms ShiQIP.msgOffset_add_width_le
#print axioms ShiQIP.σSw
#print axioms ShiQIP.coinW_val
#print axioms ShiQIP.outW_val
#print axioms ShiQIP.caW_val
#print axioms ShiQIP.Φ_swR
#print axioms ShiQIP.MBR
#print axioms ShiQIP.hPriv_le_of_inReg
#print axioms ShiQIP.mbSplit
#print axioms ShiQIP.memSplit
#print axioms ShiQIP.PA
#print axioms ShiQIP.PA_mem
#print axioms ShiQIP.PA_mulVec
#print axioms ShiQIP.tv_Φ
#print axioms ShiQIP.wires_lt_of_isSome
#print axioms ShiQIP.isSome_mono
#print axioms ShiQIP.relabel_id
#print axioms ShiQIP.notMem_support_of_filterMap
#print axioms ShiQIP.Avoid
#print axioms ShiQIP.Avoid.append
#print axioms ShiQIP.avoid_nil
#print axioms ShiQIP.avoid_of_d
#print axioms ShiQIP.avoid_swapRange
#print axioms ShiQIP.dI
#print axioms ShiQIP.filterMap_dBlock
#print axioms ShiQIP.instrInv_map
#print axioms ShiQIP.adjointInstrs_map
#print axioms ShiQIP.filterMap_adjDBlock
#print axioms ShiQIP.runLayer_dBlock
#print axioms ShiQIP.runLayer_adjDBlock
#print axioms ShiQIP.hPay_ge
#print axioms ShiQIP.hPay_add_le
#print axioms ShiQIP.runLayer_swapMsg
#print axioms ShiQIP.avoid_swapMsg
#print axioms ShiQIP.Φ_coin_ne
#print axioms ShiQIP.clean_Φ
#print axioms ShiQIP.coinW_ne_caW
#print axioms ShiQIP.filterMap_onF
#print axioms ShiQIP.filterMap_onB
#print axioms ShiQIP.supp_of_avoid
#print axioms ShiQIP.DOp
#print axioms ShiQIP.Acts
#print axioms ShiQIP.Acts.append
#print axioms ShiQIP.acts_nil
#print axioms ShiQIP.runLayer_onF_Φ
#print axioms ShiQIP.runLayer_onB_Φ
#print axioms ShiQIP.swOp
#print axioms ShiQIP.bOp
#print axioms ShiQIP.bOpH
#print axioms ShiQIP.ifOp
#print axioms ShiQIP.fwdOp
#print axioms ShiQIP.bwdOp
#print axioms ShiQIP.wd_le_hw_fwd
#print axioms ShiQIP.wd_le_hw_bwd
#print axioms ShiQIP.acts_avoid_swap
#print axioms ShiQIP.acts_avoid_dBlock
#print axioms ShiQIP.acts_avoid_adjDBlock
#print axioms ShiQIP.acts_avoid_fwdStep
#print axioms ShiQIP.acts_avoid_bwdStep
#print axioms ShiQIP.runLayer_hBlock_mid
#print axioms ShiQIP.blocks_getD_halve
#print axioms ShiQIP.kron_layer_mulVec
#print axioms ShiQIP.blockMat_halve_Φ
#print axioms ShiQIP.runLayer_add
#print axioms ShiQIP.runLayer_smul
#print axioms ShiQIP.inReg_zero_iff
#print axioms ShiQIP.regOf
#print axioms ShiQIP.cvec
#print axioms ShiQIP.cutVec
#print axioms ShiQIP.tv_zero
#print axioms ShiQIP.swap0
#print axioms ShiQIP.swap0_eq
#print axioms ShiQIP.hPriv_add_W_le
#print axioms ShiQIP.Φ_false_cut
#print axioms ShiQIP.runLayer_swap0
#print axioms ShiQIP.update_coin_ctlOK
#print axioms ShiQIP.workPart_update_coin
#print axioms ShiQIP.msgPart_update_coin
#print axioms ShiQIP.Φ_update_coin
#print axioms ShiQIP.Φ_split
#print axioms ShiQIP.runLayer_h_coin
#print axioms ShiQIP.total_pos
#print axioms ShiQIP.copyW
#print axioms ShiQIP.copyW_val
#print axioms ShiQIP.hPriv_le_copyW
#print axioms ShiQIP.flipZ
#print axioms ShiQIP.flipZ_flipZ
#print axioms ShiQIP.coinW_ne_copyW
#print axioms ShiQIP.runLayer_cnot_copy
#print axioms ShiQIP.filterMap_h_cnot
#print axioms ShiQIP.runLayer_hBlock_one
#print axioms ShiQIP.outD
#print axioms ShiQIP.outD_val
#print axioms ShiQIP.outD_ne_outW
#print axioms ShiQIP.finF
#print axioms ShiQIP.finB
#print axioms ShiQIP.finFOp
#print axioms ShiQIP.finBOp
#print axioms ShiQIP.acts_avoid_finF
#print axioms ShiQIP.acts_avoid_finB
#print axioms ShiQIP.avoid_cnot_out
#print axioms ShiQIP.filterMap_cnot_out
#print axioms ShiQIP.runLayer_onF_fin
#print axioms ShiQIP.runLayer_zero
#print axioms ShiQIP.runLayer_vanish
#print axioms ShiQIP.runLayer_onB_fin
#print axioms ShiQIP.runLayer_support
#print axioms ShiQIP.asm
#print axioms ShiQIP.ctlOK_asm
#print axioms ShiQIP.workPart_asm
#print axioms ShiQIP.msgPart_asm
#print axioms ShiQIP.asm_eq
#print axioms ShiQIP.asm_injective
#print axioms ShiQIP.sum_Φ
#print axioms ShiQIP.lt_of_mem_held0
#print axioms ShiQIP.mem_hAnc
#print axioms ShiQIP.lt_of_mem_hAnc
#print axioms ShiQIP.ztS
#print axioms ShiQIP.ztA
#print axioms ShiQIP.map_val_ztS
#print axioms ShiQIP.map_val_ztA
#print axioms ShiQIP.mem_ztA
#print axioms ShiQIP.mem_ztS
#print axioms ShiQIP.nodup_zt
#print axioms ShiQIP.length_zt
#print axioms ShiQIP.ztGates_eq
#print axioms ShiQIP.runLayer_ztGates
#print axioms ShiQIP.outW_ne_coinW
#print axioms ShiQIP.outW_notMem_ztS
#print axioms ShiQIP.ztFun_apply_ne
#print axioms ShiQIP.ztFun_involutive
#print axioms ShiQIP.zero0_iff_all
#print axioms ShiQIP.anc_ne
#print axioms ShiQIP.Φ_dirty
#print axioms ShiQIP.norm_sq_add_of_mul
#print axioms ShiQIP.ztZ
#print axioms ShiQIP.outC
#print axioms ShiQIP.ztZ_ztZ
#print axioms ShiQIP.outC_outC
#print axioms ShiQIP.sum_invol
#print axioms ShiQIP.accept_slice
#print axioms ShiQIP.σSw_involutive
#print axioms ShiQIP.gsplit_fst_eq
#print axioms ShiQIP.exists_turn_sw
#print axioms ShiQIP.flipOp
#print axioms ShiQIP.exists_turn_flip
#print axioms ShiQIP.proverOp
#print axioms ShiQIP.exists_turn_prover
#print axioms ShiQIP.exists_turn_ifOp
#print axioms ShiQIP.tfOp
#print axioms ShiQIP.tbOp
#print axioms ShiQIP.sufOp_succ'
#print axioms ShiQIP.bOpH_flip
#print axioms ShiQIP.tv_lin
#print axioms ShiQIP.kron_lin
#print axioms ShiQIP.hRun
#print axioms ShiQIP.hRun_zero
#print axioms ShiQIP.gF
#print axioms ShiQIP.gB
#print axioms ShiQIP.gF_succ
#print axioms ShiQIP.gB_succ
#print axioms ShiQIP.fH
#print axioms ShiQIP.bH
#print axioms ShiQIP.hRun_eq
#print axioms ShiQIP.hBlock_last
#print axioms ShiQIP.hRun_final
#print axioms ShiQIP.outBit_halve
#print axioms ShiQIP.preOp_adj_halve
#print axioms ShiQIP.accept_hRun
#print axioms ShiQIP.regOfE
#print axioms ShiQIP.nsq_cutVec
#print axioms ShiQIP.turnOp_conjTranspose
#print axioms ShiQIP.turnOp_one
#print axioms ShiQIP.exists_UF
#print axioms ShiQIP.exists_UB
#print axioms ShiQIP.pureRun_dilateU_hRun
#print axioms ShiQIP.sum_norm_init
#print axioms ShiQIP.accept_halve_le
#print axioms ShiQIP.value_halve_le
