import QIP.Uniform.GatePT

/-! Fresh-import audit for the Q34 library of polynomial-time functions (naturals, lists, folds,
syntax representations, the encoder and the total decoder, description fields, the checker,
gate-list transformations): statement types, then transitive axioms. -/

open ShiQIP ShiQIP.Uniform

#check (PT.encodeU : PT ShiQIP.encode)
#check (PT.decU : PT dec)
#check (dec_encode : ∀ d : Desc, dec (encode d) = d)
#check (@PT.foldl_gen : ∀ {α β ι : Type} [Rep α] [Rep β] [Rep ι] {step : β × α → β} {s : ι → β}
  {xs : ι → List α}, PT step → PT s → PT xs → (∃ B : Polynomial ℕ, ∀ a k,
    (enc (foldS step (s a) ((xs a).take k))).length ≤ B.eval (enc a).length) →
  PT fun a => foldS step (s a) (xs a))

#print axioms ShiQIP.Uniform.toV_V
#print axioms ShiQIP.Uniform.enc_V
#print axioms ShiQIP.Uniform.vfst
#print axioms ShiQIP.Uniform.vsnd
#print axioms ShiQIP.Uniform.isNode
#print axioms ShiQIP.Uniform.constM_runs'
#print axioms ShiQIP.Uniform.peekR
#print axioms ShiQIP.Uniform.caseM
#print axioms ShiQIP.Uniform.caseM_node
#print axioms ShiQIP.Uniform.caseM_leaf
#print axioms ShiQIP.Uniform.PT.vfstU
#print axioms ShiQIP.Uniform.PT.vsndU
#print axioms ShiQIP.Uniform.PT.isNodeU
#print axioms ShiQIP.Uniform.PT.ofV
#print axioms ShiQIP.Uniform.PT.toV
#print axioms ShiQIP.Uniform.PT.of_eq
#print axioms ShiQIP.Uniform.PT.congrOut
#print axioms ShiQIP.Uniform.PT.comp₂
#print axioms ShiQIP.Uniform.enc_nat_length
#print axioms ShiQIP.Uniform.enc_pair_length
#print axioms ShiQIP.Uniform.enc_cons_length
#print axioms ShiQIP.Uniform.enc_bool_length
#print axioms ShiQIP.Uniform.enc_unit
#print axioms ShiQIP.Uniform.foldS_take_le
#print axioms ShiQIP.Uniform.PT.foldl_add
#print axioms ShiQIP.Uniform.PT.foldl_unif
#print axioms ShiQIP.Uniform.PT.fp_id
#print axioms ShiQIP.Uniform.PT.fp_const
#print axioms ShiQIP.Uniform.PT.fp_comp
#print axioms ShiQIP.Uniform.PT.fp_pair
#print axioms ShiQIP.Uniform.PT.fp_fst
#print axioms ShiQIP.Uniform.PT.fp_snd
#print axioms ShiQIP.Uniform.PT.fp_ite
#print axioms ShiQIP.Uniform.PT.fp_ite'
#print axioms ShiQIP.Uniform.enc_replicate_unit
#print axioms ShiQIP.Uniform.PT.units
#print axioms ShiQIP.Uniform.PT.succU
#print axioms ShiQIP.Uniform.PT.predU
#print axioms ShiQIP.Uniform.PT.posU
#print axioms ShiQIP.Uniform.PT.fp_succ
#print axioms ShiQIP.Uniform.PT.fp_pred
#print axioms ShiQIP.Uniform.PT.fp_pos
#print axioms ShiQIP.Uniform.PT.notU
#print axioms ShiQIP.Uniform.PT.fp_not
#print axioms ShiQIP.Uniform.PT.fp_and
#print axioms ShiQIP.Uniform.PT.fp_or
#print axioms ShiQIP.Uniform.foldS_succ
#print axioms ShiQIP.Uniform.foldS_pred
#print axioms ShiQIP.Uniform.PT.addU
#print axioms ShiQIP.Uniform.PT.subU
#print axioms ShiQIP.Uniform.PT.fp_add
#print axioms ShiQIP.Uniform.PT.fp_sub
#print axioms ShiQIP.Uniform.PT.fp_le
#print axioms ShiQIP.Uniform.PT.fp_lt
#print axioms ShiQIP.Uniform.PT.fp_eq
#print axioms ShiQIP.Uniform.PT.fp_max
#print axioms ShiQIP.Uniform.PT.fp_min
#print axioms ShiQIP.Uniform.PT.fp_toV
#print axioms ShiQIP.Uniform.PT.fp_isNode
#print axioms ShiQIP.Uniform.PT.fp_vfst
#print axioms ShiQIP.Uniform.PT.fp_vsnd
#print axioms ShiQIP.Uniform.PT.fp_cons
#print axioms ShiQIP.Uniform.PT.isEmptyU
#print axioms ShiQIP.Uniform.PT.fp_isEmpty
#print axioms ShiQIP.Uniform.PT.tailU
#print axioms ShiQIP.Uniform.PT.fp_tail
#print axioms ShiQIP.Uniform.PT.headDU
#print axioms ShiQIP.Uniform.PT.fp_headD
#print axioms ShiQIP.Uniform.foldS_length
#print axioms ShiQIP.Uniform.PT.lengthU
#print axioms ShiQIP.Uniform.PT.fp_length
#print axioms ShiQIP.Uniform.foldS_rev
#print axioms ShiQIP.Uniform.PT.revOnto
#print axioms ShiQIP.Uniform.PT.fp_reverse
#print axioms ShiQIP.Uniform.PT.fp_append
#print axioms ShiQIP.Uniform.foldS_map
#print axioms ShiQIP.Uniform.PT.mapU
#print axioms ShiQIP.Uniform.PT.fp_map
#print axioms ShiQIP.Uniform.foldS_flatten
#print axioms ShiQIP.Uniform.enc_append_length
#print axioms ShiQIP.Uniform.PT.flattenU
#print axioms ShiQIP.Uniform.PT.fp_flatten
#print axioms ShiQIP.Uniform.PT.fp_flatMap
#print axioms ShiQIP.Uniform.foldS_sum
#print axioms ShiQIP.Uniform.PT.sumU
#print axioms ShiQIP.Uniform.PT.fp_sum
#print axioms ShiQIP.Uniform.enc_tail_le
#print axioms ShiQIP.Uniform.foldS_drop
#print axioms ShiQIP.Uniform.PT.dropU
#print axioms ShiQIP.Uniform.PT.fp_drop
#print axioms ShiQIP.Uniform.getD_eq_headD_drop
#print axioms ShiQIP.Uniform.PT.fp_getD
#print axioms ShiQIP.Uniform.foldS_take
#print axioms ShiQIP.Uniform.PT.takeU
#print axioms ShiQIP.Uniform.PT.fp_take
#print axioms ShiQIP.Uniform.foldS_filter
#print axioms ShiQIP.Uniform.PT.filterU
#print axioms ShiQIP.Uniform.PT.fp_filter
#print axioms ShiQIP.Uniform.foldS_all
#print axioms ShiQIP.Uniform.PT.allU
#print axioms ShiQIP.Uniform.PT.fp_all
#print axioms ShiQIP.Uniform.PT.foldl_gen
#print axioms ShiQIP.Uniform.enc_list_le
#print axioms ShiQIP.Uniform.foldS_range
#print axioms ShiQIP.Uniform.PT.rangeU
#print axioms ShiQIP.Uniform.PT.fp_range
#print axioms ShiQIP.Uniform.foldS_replicate
#print axioms ShiQIP.Uniform.PT.replicateU
#print axioms ShiQIP.Uniform.PT.fp_replicate
#print axioms ShiQIP.Uniform.foldS_parity
#print axioms ShiQIP.Uniform.PT.oddU
#print axioms ShiQIP.Uniform.PT.fp_mod2
#print axioms ShiQIP.Uniform.foldS_zip
#print axioms ShiQIP.Uniform.enc_zip_le
#print axioms ShiQIP.Uniform.enc_drop_le
#print axioms ShiQIP.Uniform.enc_take_le
#print axioms ShiQIP.Uniform.zipWith_eq_map_zip'
#print axioms ShiQIP.Uniform.PT.zipU
#print axioms ShiQIP.Uniform.PT.fp_zip
#print axioms ShiQIP.Uniform.PT.fp_zipWith
#print axioms ShiQIP.Uniform.foldS_mul
#print axioms ShiQIP.Uniform.PT.mulU
#print axioms ShiQIP.Uniform.PT.fp_mul
#print axioms ShiQIP.Uniform.PT.reenc
#print axioms ShiQIP.Dir.toB
#print axioms ShiQIP.Dir.ofB
#print axioms ShiQIP.Dir.ofB_toB
#print axioms ShiQIP.Uniform.PT.dirToB
#print axioms ShiQIP.Uniform.PT.dirOfB
#print axioms ShiQIP.Uniform.PT.fp_dirToB
#print axioms ShiQIP.Uniform.PT.fp_dirOfB
#print axioms ShiQIP.Uniform.PT.msgDir
#print axioms ShiQIP.Uniform.PT.msgWidth
#print axioms ShiQIP.Uniform.PT.msgMk
#print axioms ShiQIP.Uniform.PT.fp_msgDir
#print axioms ShiQIP.Uniform.PT.fp_msgWidth
#print axioms ShiQIP.Uniform.PT.fp_msgMk
#print axioms ShiQIP.Gate.cd
#print axioms ShiQIP.Gate.ofCd
#print axioms ShiQIP.Gate.ofCd_cd
#print axioms ShiQIP.Uniform.PT.gateCd
#print axioms ShiQIP.Uniform.PT.gateOfCd
#print axioms ShiQIP.Uniform.PT.fp_gateCd
#print axioms ShiQIP.Uniform.PT.fp_gateOfCd
#print axioms ShiQIP.Uniform.PT.fp_gate_h
#print axioms ShiQIP.Uniform.PT.fp_gate_s
#print axioms ShiQIP.Uniform.PT.fp_gate_t
#print axioms ShiQIP.Uniform.PT.fp_gate_x
#print axioms ShiQIP.Uniform.PT.fp_gate_cnot
#print axioms ShiQIP.Desc.tup
#print axioms ShiQIP.Uniform.PT.descTup
#print axioms ShiQIP.Uniform.PT.descMk
#print axioms ShiQIP.Uniform.PT.fp_descTup
#print axioms ShiQIP.Uniform.PT.fp_priv
#print axioms ShiQIP.Uniform.PT.fp_out
#print axioms ShiQIP.Uniform.PT.fp_msgs
#print axioms ShiQIP.Uniform.PT.fp_blocks
#print axioms ShiQIP.Uniform.PT.fp_descMk
#print axioms ShiQIP.Uniform.PT.fp_encNat
#print axioms ShiQIP.Uniform.encDir_eq
#print axioms ShiQIP.Uniform.PT.fp_encDir
#print axioms ShiQIP.Uniform.PT.fp_encMsg
#print axioms ShiQIP.Uniform.encGate_eq
#print axioms ShiQIP.Uniform.PT.fp_encGate
#print axioms ShiQIP.Uniform.PT.encListU
#print axioms ShiQIP.Uniform.PT.fp_encBlock
#print axioms ShiQIP.Uniform.PT.encodeU
#print axioms ShiQIP.Uniform.natStep
#print axioms ShiQIP.Uniform.pNat
#print axioms ShiQIP.Uniform.foldS_natStep_done
#print axioms ShiQIP.Uniform.foldS_natStep
#print axioms ShiQIP.Uniform.pNat_encNat
#print axioms ShiQIP.Uniform.PT.natStepU
#print axioms ShiQIP.Uniform.PT.pNatU
#print axioms ShiQIP.Uniform.PT.fp_pNat
#print axioms ShiQIP.Uniform.enc_prod_length
#print axioms ShiQIP.Uniform.ParserB
#print axioms ShiQIP.Uniform.enc_suffix_le
#print axioms ShiQIP.Uniform.length_le_enc_str
#print axioms ShiQIP.Uniform.foldS_natStep_spec
#print axioms ShiQIP.Uniform.pNat_bound
#print axioms ShiQIP.Uniform.listStep
#print axioms ShiQIP.Uniform.pList
#print axioms ShiQIP.Uniform.foldS_listStep
#print axioms ShiQIP.Uniform.pList_encList
#print axioms ShiQIP.Uniform.foldS_listStep_bound
#print axioms ShiQIP.Uniform.pList_bound
#print axioms ShiQIP.Uniform.PT.listStepU
#print axioms ShiQIP.Uniform.PT.pListU
#print axioms ShiQIP.Uniform.pMsg
#print axioms ShiQIP.Uniform.pGate
#print axioms ShiQIP.Uniform.pDesc
#print axioms ShiQIP.Uniform.dec
#print axioms ShiQIP.Uniform.pMsg_encMsg
#print axioms ShiQIP.Uniform.pGate_encGate
#print axioms ShiQIP.Uniform.dec_encode
#print axioms ShiQIP.Uniform.PT.pMsgU
#print axioms ShiQIP.Uniform.PT.pGateU
#print axioms ShiQIP.Uniform.pMsg_bound
#print axioms ShiQIP.Uniform.enc_gate_length
#print axioms ShiQIP.Uniform.enc_ofCd_le
#print axioms ShiQIP.Uniform.pGate_bound
#print axioms ShiQIP.Uniform.PT.fp_pMsg
#print axioms ShiQIP.Uniform.PT.fp_pListMsg
#print axioms ShiQIP.Uniform.PT.pBlockU
#print axioms ShiQIP.Uniform.PT.fp_pListBlock
#print axioms ShiQIP.Uniform.PT.decU
#print axioms ShiQIP.Uniform.PT.fp_numMsgs
#print axioms ShiQIP.Uniform.PT.fp_totalWires
#print axioms ShiQIP.Uniform.PT.fp_msgOffset
#print axioms ShiQIP.Uniform.msgWidth_eq'
#print axioms ShiQIP.Uniform.PT.fp_msgWidth'
#print axioms ShiQIP.Uniform.PT.fp_gateCount
#print axioms ShiQIP.Uniform.PT.fp_decide_and
#print axioms ShiQIP.Uniform.PT.fp_decide_or
#print axioms ShiQIP.Uniform.PT.fp_decide_not
#print axioms ShiQIP.Uniform.PT.fp_decide_bool
#print axioms ShiQIP.Uniform.PT.fp_bne_nat
#print axioms ShiQIP.Uniform.PT.fp_bne_bool
#print axioms ShiQIP.Uniform.PT.fp_beq_bool
#print axioms ShiQIP.Uniform.dirOK
#print axioms ShiQIP.Uniform.dirOK_eq
#print axioms ShiQIP.Uniform.heldStep
#print axioms ShiQIP.Uniform.foldS_heldStep
#print axioms ShiQIP.Uniform.PT.dirOKU
#print axioms ShiQIP.Uniform.PT.fp_dirOK
#print axioms ShiQIP.Uniform.PT.heldStepU
#print axioms ShiQIP.Uniform.PT.msgHeldU
#print axioms ShiQIP.Uniform.PT.fp_msgHeld
#print axioms ShiQIP.Uniform.PT.fp_held
#print axioms ShiQIP.Uniform.okBool_eq
#print axioms ShiQIP.Uniform.PT.fp_okBool
#print axioms ShiQIP.Uniform.alternates_eq
#print axioms ShiQIP.Uniform.blocksOkFrom_eq
#print axioms ShiQIP.Uniform.PT.fp_check
#print axioms ShiQIP.Uniform.stdSchedule_eq
#print axioms ShiQIP.Uniform.PT.fp_stdSchedule
#print axioms ShiQIP.Uniform.dirList_eq_iff
#print axioms ShiQIP.Uniform.PT.fp_hasSchedule
#print axioms ShiQIP.Uniform.relabel_eq
#print axioms ShiQIP.Uniform.PT.fp_relabel
#print axioms ShiQIP.Uniform.inv_eq
#print axioms ShiQIP.Uniform.PT.fp_inv
#print axioms ShiQIP.Uniform.PT.fp_adjointGates
#print axioms ShiQIP.Uniform.PT.fp_swapGates
#print axioms ShiQIP.Uniform.PT.fp_tdgGates
#print axioms ShiQIP.Uniform.PT.fp_sdgGates
#print axioms ShiQIP.Uniform.PT.fp_cczGates
#print axioms ShiQIP.Uniform.PT.fp_toffoliGates
#print axioms ShiQIP.Uniform.PT.fp_ncaGates
#print axioms ShiQIP.Uniform.ctrlGate_eq
#print axioms ShiQIP.Uniform.PT.fp_ctrlGate
#print axioms ShiQIP.Uniform.PT.fp_ctrlGates
#print axioms ShiQIP.Uniform.ztTriples
#print axioms ShiQIP.Uniform.ztClosed
#print axioms ShiQIP.Uniform.ztGates_eq
#print axioms ShiQIP.Uniform.PT.fp_ztGates
#print axioms ShiQIP.Uniform.PT.fp_psum
#print axioms ShiQIP.Uniform.PT.fp_zw
#print axioms ShiQIP.Uniform.segIdx_eq
#print axioms ShiQIP.Uniform.PT.fp_segIdx
